#!/bin/bash -ex
##############################################################################
# Script for doing a ParaView source build on Linux/OSX
#
# BUILD_THREADS is set in the Jenkins node configuration
# NODE_LABELS should be set to indicate the OS
#
# It should be invoked as
#   - buildscript [<build-dir>]
# where <build-dir> is an optional build directory (default=$HOME/build)
#
# This will create a directory for the PARAVIEW_DIR configuration
# variable like:
#
# OSX:   /Users/builder/<build-dir>/ParaView-X.Y.Z
# Linux: /home/builder/<build-dir>/ParaView-X.Y.Z
##############################################################################

#get script directory
SCRIPT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)

# Set the ParaView version to build
PV_VERSION=v5.0.0-RC1
PV_VERSION2=${PV_VERSION%.*}
PV_VERSION3=${PV_VERSION/v/}

# Set the source and build directories
BUILDER=builder

if [[ $(uname) == "Darwin" ]]; then
  HOME_DIR=/Users/${BUILDER}
else
  HOME_DIR=/home/${BUILDER}
fi

SRC_DIR=${HOME_DIR}/src
if [ $# -eq "1" ]; then
  BUILD_DIR=$1
else
  BUILD_DIR=${HOME_DIR}/build
fi

# Print some things
cmake --version

# Setup directories if they don't exist.
[[ -d ${SRC_DIR} ]] || mkdir ${SRC_DIR}
[[ -d ${BUILD_DIR} ]] || mkdir ${BUILD_DIR}

# Grab source package and unpack
cd ${SRC_DIR}
PARAVIEW_SRC=ParaView-${PV_VERSION}-source
if [[ ! -d ${PARAVIEW_SRC} ]]; then
 git clone https://gitlab.kitware.com/paraview/paraview.git ${PARAVIEW_SRC}
 cd ${PARAVIEW_SRC}
else
 cd ${PARAVIEW_SRC}
 # Update paraview branches && tags
 # Tags need to be separate as git < 1.9 fetches only tags with -t
 git fetch -p
 git fetch -t
 # RHEL6 has git 1.7 that doesn't know about submodule recursion
 git submodule foreach git fetch -p
 git submodule foreach git fetch -t
fi
git checkout ${PV_VERSION}
git submodule update --init --recursive
#remove any changes from previous patches
git reset --hard
git submodule foreach git reset --hard

# Go to build area, setup and run
cd ${BUILD_DIR}
PARAVIEW_BUILD=ParaView-${PV_VERSION3}
[[ -d ${PARAVIEW_BUILD} ]] || mkdir ${PARAVIEW_BUILD}
cd ${PARAVIEW_BUILD}

COMMON_CACHE_FILE=${SCRIPT_DIR}/common.cmake
OSX_CACHE_FILE=${SCRIPT_DIR}/osx.cmake
LINUX_CACHE_FILE=${SCRIPT_DIR}/linux.cmake

if [[ ${NODE_LABELS} == *rhel6* ]]; then
  SCL_ON_RHEL6="scl enable mantidlibs34"
else
  SCL_ON_RHEL6="eval"
fi

if [[ $(uname) == "Darwin" ]]; then
  $SCL_ON_RHEL6 "cmake -C${COMMON_CACHE_FILE} -C${OSX_CACHE_FILE} ${SRC_DIR}/${PARAVIEW_SRC}"
else
  $SCL_ON_RHEL6 "cmake -C${COMMON_CACHE_FILE} -C${LINUX_CACHE_FILE} ${SRC_DIR}/${PARAVIEW_SRC}"
fi

$SCL_ON_RHEL6 "make -j ${BUILD_THREADS}"
